apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque  
data:
  AWS_SECRET_KEY_ID: QUtJQTZHQk1DVTdaQktNVVYyRkg=
  AWS_SECRET_ACCESS_KEY: TGJWcko4eVFpdzI4MS9RdklWSDhBODQ1Q1FnVDR4bk4rK1hLSVRDdw==
  JWT_SECRET: "SjN2MHZZNmhGdjluOVE2azVyNnNGNHFZekY5SHEzdDJzSjFuSzJtQjVwQT0="

