{{- range .Values.services }}
apiVersion: apps/v1
kind: Service
metadata:
  name: {{ .name }}-service
spec: 
  type: ClusterIP
  selector:
    component: {{ .name }}
  ports:
    - port: {{ .port }}  
      targetPort: {{ .port }}
---      
{{- end }}