image:
  tag: "8d56dba"

services:
  - name: admin-service
    imagename: streamingapp-admin
    replicaCount: 1
    port: 3003
    targetPort: 3003
    path: /api/admin
    servicetype: ClusterIP
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: ADMIN_SERVICE_PORT
      - name: MONGO_URI
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: MONGO_URI
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: secrets
            key: JWT_SECRET
      - name: CLIENT_URL
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: CLIENT_URL
      - name: AWS_SECRET_KEY_ID
        valueFrom:
          secretKeyRef:
            name: secrets
            key: AWS_SECRET_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: secrets
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: AWS_REGION
      - name: AWS_S3_BUCKET
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: AWS_S3_BUCKET
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  
  - name: chat-service
    imagename: streamingapp-chat
    replicaCount: 1
    port: 3004
    targetPort: 3004
    path: /api/chat
    servicetype: ClusterIP
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: CHAT_SERVICE_PORT
      - name: MONGO_URI
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: MONGO_URI
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: secrets
            key: JWT_SECRET
      - name: CLIENT_URL
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: CLIENT_URL
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  
  - name: streaming-service
    imagename: streamingapp-streaming
    replicaCount: 1
    port: 3002
    targetPort: 3002
    path: /api/streaming
    servicetype: ClusterIP
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: STREAMING_SERVICE_PORT
      - name: MONGO_URI
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: MONGO_URI
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: secrets
            key: JWT_SECRET
      - name: CLIENT_URL
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: CLIENT_URL
      - name: AWS_SECRET_KEY_ID
        valueFrom:
          secretKeyRef:
            name: secrets
            key: AWS_SECRET_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: secrets
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_REGION
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: AWS_REGION
      - name: AWS_S3_BUCKET
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: AWS_S3_BUCKET
      - name: AWS_CDN_URL
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: AWS_CDN_URL
      - name: STREAMING_PUBLIC_URL
        valueFrom:
          configMapKeyRef:
            name: configmap
            key: STREAMING_PUBLIC_URL     
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  
  
  