{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec: 
  type: {{ .servicetype }}
  selector:
    component: {{ .name }}
  ports:
    - port: {{ .port }}  
      targetPort: {{ .targetPort }}
---      
{{- end }}